name: BMI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Wähle die gewünschte Node.js-Version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run Jest tests
        run: npm test  # Führe Jest-Tests aus

  